version: '3.9'
services:
  postgres:
    container_name: subscriber-database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriber
    ports:
      - '5432:5432'
